# Site settings
title: "Agustin Crovetto"
description: "Professional resume and portfolio"
url: "https://agcrov.github.io"
baseurl: "/portfolio"

# GitHub Pages settings
remote_theme: b2a3e8/jekyll-theme-console
markdown: kramdown
highlighter: rouge

# jekyll-theme-console settings
header_pages:
  - index.md
  - about.md
  - projects.md
  - contact.md

# Style options: black (default), dark, hacker, light, gruvbox-dark, gruvbox-light
style: hacker

# Optional: Add your social links
github_username: yourusername
linkedin_username: yourprofile

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - AGENT.local.md 